# Generated by Django 2.0.7 on 2018-09-05 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userpi',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
